plugins:
  jqlogs:
    shortCut: Ctrl-J
    confirm: false
    description: "Logs (jq)"
    scopes:
      - po
    command: sh
    background: false
    args:
      - -c
      - "kubectl logs $NAME -n $NAMESPACE --context $CONTEXT | jq -r . | bat"
  remove_finalizers:
    shortCut: Ctrl-F
    confirm: true
    description: Removes finalizers
    scopes:
      - all
    background: true
    command: kubectl
    args:
      - patch
      - --context
      - $CONTEXT
      - --namespace
      - $NAMESPACE
      - $RESOURCE_NAME
      - $NAME
      - -p
      - '{"metadata":{"finalizers":null}}'
      - --type
      - merge
  debug_container:
    shortCut: Shift-D
    description: Add debug container
    dangerous: true
    scopes:
      - containers
    command: bash
    background: false
    confirm: true
    args:
      - -c
      - "kubectl debug -it --context $CONTEXT -n=$NAMESPACE $POD --target=$NAME --image=nicolaka/netshoot:v0.12 --share-processes -- bash"
  debug_pod:
    shortCut: Shift-D
    confirm: false
    description: "Add Debug container"
    scopes:
      - po
    command: kubectl
    background: false
    args:
      - debug
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      - -it
      - --image=nicolaka/netshoot
